// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScreenTest
void ui_ScreenTest_screen_init(void);
void ui_event_ScreenTest(lv_event_t * e);
extern lv_obj_t * ui_ScreenTest;
extern lv_obj_t * ui_LabelHelloWorld;
extern lv_obj_t * ui_LabelBrightness;
void ui_event_SliderBrightness(lv_event_t * e);
extern lv_obj_t * ui_SliderBrightness;
extern lv_obj_t * ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
