// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenTest_screen_init(void)
{
    ui_ScreenTest = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_ScreenTest, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenTest, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_LabelHelloWorld = lv_label_create(ui_ScreenTest);
    lv_obj_set_height(ui_LabelHelloWorld, 100);
    lv_obj_set_width(ui_LabelHelloWorld, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_LabelHelloWorld, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHelloWorld, "Hello World");
    lv_obj_set_style_text_font(ui_LabelHelloWorld, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBrightness = lv_label_create(ui_ScreenTest);
    lv_obj_set_width(ui_LabelBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBrightness, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBrightness, "");
    lv_obj_set_style_text_font(ui_LabelBrightness, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderBrightness = lv_slider_create(ui_ScreenTest);
    lv_slider_set_range(ui_SliderBrightness, 2, 255);
    lv_slider_set_value(ui_SliderBrightness, 2, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBrightness, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBrightness, 600);
    lv_obj_set_height(ui_SliderBrightness, 20);
    lv_obj_set_align(ui_SliderBrightness, LV_ALIGN_CENTER);


    lv_obj_add_event_cb(ui_SliderBrightness, ui_event_SliderBrightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenTest, ui_event_ScreenTest, LV_EVENT_ALL, NULL);

}
