// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENTEST_H
#define UI_SCREENTEST_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenTest
extern void ui_ScreenTest_screen_init(void);
extern void ui_ScreenTest_screen_destroy(void);
extern void ui_event_ScreenTest(lv_event_t * e);
extern lv_obj_t * ui_ScreenTest;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_LabelHelloWorld;
extern lv_obj_t * ui_LabelCounter;
extern lv_obj_t * ui_Panel2;
extern void ui_event_SliderBrightness(lv_event_t * e);
extern lv_obj_t * ui_SliderBrightness;
extern lv_obj_t * ui_LabelBrightness;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

